### ISSUE TITLE
does not build on macOS

### ISSUE THREAD

**Issue by flurie** [andreymulik/sdp#1]
The library does not build on macOS with ghc 8.10.7.

```
src/SDP/Unboxed.hs:656:373: error:
    Not in scope: data constructor ‘Type’
    |
656 | deriving_instance_Unboxed(CChar)
    |

                                                               ^^^^

src/SDP/Unboxed.hs:657:380: error:
    Not in scope: data constructor ‘Type’
    |
657 | deriving_instance_Unboxed(CSChar)
    |

                                                                      ^^^^

[rest of errors omitted for brevity]
```

I believe the root cause is that the clang c-preprocessor has an issue with the style of macros used. I was able to get this to build using cpphs in place of cpp.

**Comment by andreymulik** [comment]
MR is accepted, a new `sdp-0.2.1.1` patch has been published, changes will also be added in a future major release of `sdp-0.3`.
